In [ ]:
import pandas as pd
import numpy as np
import datetime
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
from datetime import datetime, time
from time import mktime as mktime

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks

In [ ]:
names = ['S' + str(format(i, '02')) for i in range(6)] # + 1 because range starts at 0
names.pop(0) # Pop the first element of the list to match the names of the files
print(names)

# Create a list of the variables and its columns
variables = ['EDA', 'HR', 'IBI','TEMP']
final_columns = {
    #'ACC': ['x', 'y', 'z'],
    'EDA': ['EDA'],
    'HR': ['HR',],
    'IBI': ['IBI', 'IBI_ms'],
    'TEMP': ['TEMP'],
}
print(variables)

['S01', 'S02', 'S03', 'S04', 'S05']
['EDA', 'HR', 'IBI', 'TEMP']

In [ ]:
df_HR = pd.read_csv(f'https://raw.githubusercontent.com/italha-d/Stress-Predict-Dataset/main/Raw_data/S01/HR.csv',header=None)
df_HR.head()
start_time = df_HR.iloc[0,0]
df2 = df_HR.T
init = df2.pop(0)
hz = df2.pop(1)
df_HR = df2.T
time = [start_time+(i*1000) for i in range(len(df_HR))]
df_HR['time'] = time
df_HR.set_index('time', inplace=True)
df_HR = df_HR.rename(columns={0: 'HR'}, inplace=False)
df_HR

                 HR
time
1.644226e+09  83.00
1.644227e+09  83.00
1.644228e+09  72.67
1.644229e+09  87.00
1.644230e+09  80.00
...             ...
1.647471e+09  83.35
1.647472e+09  83.33
1.647473e+09  83.28
1.647474e+09  83.22
1.647475e+09  83.23

[3250 rows x 1 columns]

In [ ]:
# Import timelogs for visualization
# This DataFrame contains the time logs for each subject responses
timelogs = pd.read_csv('Time_logs.csv')
#timelogs = timelogs.drop(0, axis=0)
#timelogs = timelogs.drop(['S. ID.','End Time','Session ID','Consent','Unnamed: 5','Date','Unnamed: 24'], axis=1)
timelogs

,S. ID.,Start Time,End Time,Session ID,Consent,Unnamed: 5,Baseline/Questionniare,Unnamed: 7,Stroop Test,Unnamed: 9,...,Hyperventilation,Unnamed: 17,Relax.2,Unnamed: 19,Questionniare,Unnamed: 21,Relax/Baseline,Unnamed: 23,Unnamed: 24,Date
0,NaN,NaN,NaN,NaN,Start,End,Start,End,Start,End,...,Start,End,Start,End,Start,End,Start,End,NaN,NaN
1,S01,9:22,10:22,1445405.0,9:22,9:27,9:39,9:43,9:29,9:34,...,10:00,10:02,10:02,10:07,10:08,10:12,10:12,10:22,Day 1,7-Feb-2022
2,S02,9:48,10:51,1445449.0,9:48,9:50,9:52,10:02,10:03,10:08,...,10:29,10:31,10:31,10:36,10:36,10:41,10:41,10:51,Day 1,7-Feb-2022
3,S03,10:50,11:50,1445450.0,10:50,10:53,10:55,11:02,11:04,11:09,...,11:28,11:30,11:30,11:35,11:35,11:40,11:40,11:50,Day 1,7-Feb-2022
4,S04,11:25,12:28,1445452.0,11:25,11:30,11:30,11:40,11:40,11:45,...,12:05,12:07,12:07,12:12,12:12,12:18,12:18,12:28,Day 1,7-Feb-2022
5,S05,9:05,10:06,1449998.0,9:05,9:10,9:12,9:22,9:23,9:29,...,9:49,9:51,9:51,9:56,9:56,10:01,10:01,10:06,Day 2,14-Feb-2022
6,S06,9:41,10:40,1450001.0,9:41,9:43,9:44,9:54,9:55,10:01,...,10:23,10:25,10:25,10:30,10:30,10:35,10:35,10:40,Day 2,14-Feb-2022
7,S07,10:25,11:26,1450002.0,10:25,10:29,10:31,10:41,10:43,10:48,...,11:09,11:11,11:11,11:16,11:16,11:21,11:21,11:26,Day 2,14-Feb-2022
8,S08,12:08,1:05,1450061.0,12:08,12:10,12:12,12:22,12:23,12:28,...,12:48,12:50,12:50,12:55,12:55,1:00,1:00,1:05,Day 2,14-Feb-2022
9,S09,12:34,1:31,1450063.0,12:34,12:36,12:38,12:48,12:49,12:54,...,1:14,1:16,1:16,1:21,1:21,1:26,1:26,1:31,Day 2,14-Feb-2022
10,S10,1:11,2:05,1450065.0,1:11,1:13,1:14,1:23,1:23,1:28,...,1:49,1:51,1:51,1:56,1:56,1:59,1:59,2:05,Day 2,14-Feb-2022
11,S11,3:15,4:15,1450169.0,3:15,3:19,3:21,3:31,3:32,3:38,...,3:58,4:00,4:01,4:06,4:06,4:10,4:10,4:15,Day 2,14-Feb-2022
12,S12,9:09,10:10,1454360.0,9:09,9:14,9:15,9:25,9:26,9:31,...,9:53,9:55,9:55,10:00,10:00,10:05,10:05,10:10,Day 3,21-Feb-2022
13,S13,11:20,12:20,1454571.0,11:20,11:25,11:25,11:35,11:35,11:42,...,12:03,12:05,12:05,12:10,12:10,12:14,12:14,12:20,Day 3,21-Feb-2022
14,S14,11:41,12:46,145474.0,11:41,11:46,11:47,11:57,12:01,12:06,...,12:28,12:30,12:31,12:36,12:36,12:42,12:42,12:46,Day 3,21-Feb-2022
15,S15,12:31,1:34,1454575.0,12:31,12:36,12:37,12:47,12:49,12:55,...,1:17,1:19,1:19,1:24,1:24,1:29,1:29,1:34,Day 3,21-Feb-2022
16,S16,1:05,2:10,1454577.0,1:05,1:10,1:13,1:23,1:26,1:31,...,1:52,1:54,1:54,2:00,2:00,2:06,2:06,2:10,Day 3,21-Feb-2022
17,S17,3:09,3:11,1454658.0,3:09,3:11,3:13,3:23,3:24,3:30,...,3:51,3:53,3:53,3:58,3:58,4:03,4:03,4:08,Day 3,21-Feb-2022
18,S18,3:30,4:31,1454661.0,3:30,3:35,3:35,3:45,3:46,3:51,...,4:14,4:16,4:16,4:21,4:21,4:26,4:26,4:31,Day 3,21-Feb-2022
19,S19,9:15,10:12,1458977.0,9:15,9:18,9:19,9:29,9:30,9:35,...,9:55,9:57,9:57,10:02,10:02,10:07,10:07,10:12,Day 4,28-Feb-2022
20,S20,9:46,10:44,1458978.0,9:46,9:49,9:50,10:00,10:01,10:07,...,10:27,10:29,10:29,10:34,10:34,10:39,10:39,10:44,Day 4,28-Feb-2022
21,S21,11:40,12:34,1459084.0,11:40,11:43,11:45,11:55,11:55,12:01,...,12:22,12:24,12:24,12:29,12:29,12:34,12:34,12:38,Day 4,28-Feb-2022
22,S22,12:16,1:10,1459085.0,12:16,12:18,12:20,12:28,12:29,12:35,...,12:55,12:57,12:57,1:02,1:02,1:06,1:06,1:10,Day 4,28-Feb-2022
23,S23,12:41,1:36,1459086.0,12:41,12:45,12:45,12:55,12:55,1:01,...,1:21,1:23,1:23,1:28,1:28,1:31,1:31,1:36,Day 4,28-Feb-2022
24,S24,2:36,3:35,1459225.0,2:36,2:38,2:40,2:50,2:51,2:57,...,3:18,3:20,3:20,3:25,3:25,3:30,3:30,3:35,Day 4,28-Feb-2022
25,S25,3:09,4:06,1459232.0,3:09,3:12,3:13,3:23,3:23,3:29,...,3:49,3:51,3:51,3:56,3:56,4:02,4:02,4:06,Day 4,28-Feb-2022
26,S26,3:37,4:35,1459230.0,3:37,3:40,3:42,3:52,3:52,3:57,...,4:18,4:20,4:20,4:25,4:25,4:28,4:28,4:35,Day 4,28-Feb-2022
27,S27,9:40,10:42,1463807.0,9:40,9:45,9:47,9:57,9:58,10:04,...,10:25,10:27,10:27,10:32,10:32,10:37,10:37,10:42,Day 5,7-Mar-2022
28,S28,12:13,1:10,1463925.0,12:13,12:17,12:17,12:27,12:27,12:33,...,12:53,12:55,12:55,1:00,1:00,1:08,1:08,1:10,Day 5,7-Mar-2022
29,S29,12:34,1:33,1463927.0,12:34,12:39,12:40,12:50,12:50,12:56,...,1:16,1:18,1:18,1:23,1:23,1:29,1:29,1:33,Day 5,7-Mar-2022
30,S30,12:53,1:54,1463929.0,12:53,12:58,1:00,1:10,1:11,1:17,...,1:37,1:39,1:39,1:44,1:44,1:50,1:50,1:54,Day 5,7-Mar-2022
31,S31,3:05,4:04,1464046.0,3:05,3:10,3:10,3:20,3:21,3:26,...,3:47,3:49,3:49,3:54,3:54,3:57,3:57,4:04,Day 5,7-Mar-2022
32,S32,3:34,4:30,1464048.0,3:34,3:37,3:37,3:47,3:47,3:53,...,4:13,4:15,4:15,4:20,4:20,4:24,4:24,4:30,Day 5,7-Mar-2022
33,S33,12:11,1:08,1465906.0,12:11,12:14,12:15,12:25,12:24,12:30,...,12:51,12:53,12:53,12:58,12:58,1:05,1:05,1:08,Day 6,9-Mar-2022
34,S34,2:30,3:35,1466048.0,2:30,2:35,2:38,2:50,2:51,2:57,...,3:18,3:20,3:20,3:25,3:25,3:30,3:30,3:35,Day 6,9-Mar-2022
35,S35,3:07,4:11,1466055.0,3:07,3:12,3:12,3:22,3:23,3:29,...,3:49,3:51,3:52,3:57,3:57,4:01,4:01,4:07,Day 6,9-Mar-2022

In [ ]:
timelogs.Date += ' ' + timelogs['Start Time']
#timelogs.Date = pd.to_datetime(timelogs['Date'])
timelogs.Date

0                   NaN
1       7-Feb-2022 9:22
2       7-Feb-2022 9:48
3      7-Feb-2022 10:50
4      7-Feb-2022 11:25
5      14-Feb-2022 9:05
6      14-Feb-2022 9:41
7     14-Feb-2022 10:25
8     14-Feb-2022 12:08
9     14-Feb-2022 12:34
10     14-Feb-2022 1:11
11     14-Feb-2022 3:15
12     21-Feb-2022 9:09
13    21-Feb-2022 11:20
14    21-Feb-2022 11:41
15    21-Feb-2022 12:31
16     21-Feb-2022 1:05
17     21-Feb-2022 3:09
18     21-Feb-2022 3:30
19     28-Feb-2022 9:15
20     28-Feb-2022 9:46
21    28-Feb-2022 11:40
22    28-Feb-2022 12:16
23    28-Feb-2022 12:41
24     28-Feb-2022 2:36
25     28-Feb-2022 3:09
26     28-Feb-2022 3:37
27      7-Mar-2022 9:40
28     7-Mar-2022 12:13
29     7-Mar-2022 12:34
30     7-Mar-2022 12:53
31      7-Mar-2022 3:05
32      7-Mar-2022 3:34
33     9-Mar-2022 12:11
34      9-Mar-2022 2:30
35      9-Mar-2022 3:07
Name: Date, dtype: object

In [ ]:
timestamp = timelogs.Date
print(timestamp)
timestamp = datetime.strptime(timestamp, '%d/%m/%Y %I:%M %p').timestamp()
Startunix = mktime(timelogs.Date.timetuple())
Startunix

0                   NaN
1       7-Feb-2022 9:22
2       7-Feb-2022 9:48
3      7-Feb-2022 10:50
4      7-Feb-2022 11:25
5      14-Feb-2022 9:05
6      14-Feb-2022 9:41
7     14-Feb-2022 10:25
8     14-Feb-2022 12:08
9     14-Feb-2022 12:34
10     14-Feb-2022 1:11
11     14-Feb-2022 3:15
12     21-Feb-2022 9:09
13    21-Feb-2022 11:20
14    21-Feb-2022 11:41
15    21-Feb-2022 12:31
16     21-Feb-2022 1:05
17     21-Feb-2022 3:09
18     21-Feb-2022 3:30
19     28-Feb-2022 9:15
20     28-Feb-2022 9:46
21    28-Feb-2022 11:40
22    28-Feb-2022 12:16
23    28-Feb-2022 12:41
24     28-Feb-2022 2:36
25     28-Feb-2022 3:09
26     28-Feb-2022 3:37
27      7-Mar-2022 9:40
28     7-Mar-2022 12:13
29     7-Mar-2022 12:34
30     7-Mar-2022 12:53
31      7-Mar-2022 3:05
32      7-Mar-2022 3:34
33     9-Mar-2022 12:11
34      9-Mar-2022 2:30
35      9-Mar-2022 3:07
Name: Date, dtype: object

TypeError: ignored